name: flutter_screen_capture
description: A new Flutter project.
version: 0.2.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: 6.1.2
  widgets_to_image:
  image_gallery_saver: 2.0.3
  share:
  permission_handler: 11.3.1
  uri_to_file: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
